services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  elearning_backend:
    build: ./backend
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build: ./backend
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - elearning_backend

  elearning_frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://178.128.89.233:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules # Important! Prevents "vite not found"
    depends_on:
      - elearning_backend